//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppReportTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class dUserProfiles
    {
        public int UserID { get; set; }
        public int ProfileID { get; set; }
        public int AccessTemplateID { get; set; }
    
        public virtual mAccessTemplates mAccessTemplates { get; set; }
        public virtual mProfiles mProfiles { get; set; }
        public virtual mUsers mUsers { get; set; }
    }
}
