//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppReportTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class mApplications
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mApplications()
        {
            this.mAccessLog = new HashSet<mAccessLog>();
            this.mOperations = new HashSet<mOperations>();
            this.mProfiles = new HashSet<mProfiles>();
        }
    
        public int ApplicationID { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public string Origin { get; set; }
        public string Version { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public bool IsReadOnly { get; set; }
        public bool ManagesDelagations { get; set; }
        public int StatusID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mAccessLog> mAccessLog { get; set; }
        public virtual mStatus mStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mOperations> mOperations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mProfiles> mProfiles { get; set; }
    }
}
