//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppReportTest
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities1 : DbContext
    {
        public Entities1()
            : base("name=Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Delegation> Delegation { get; set; }
        public virtual DbSet<dUserProfiles> dUserProfiles { get; set; }
        public virtual DbSet<mAccessLog> mAccessLog { get; set; }
        public virtual DbSet<mAccessTemplates> mAccessTemplates { get; set; }
        public virtual DbSet<mApplications> mApplications { get; set; }
        public virtual DbSet<mOperations> mOperations { get; set; }
        public virtual DbSet<mProfiles> mProfiles { get; set; }
        public virtual DbSet<mSmartCardRoles> mSmartCardRoles { get; set; }
        public virtual DbSet<mSmartCards> mSmartCards { get; set; }
        public virtual DbSet<mStatus> mStatus { get; set; }
        public virtual DbSet<mStatusTypes> mStatusTypes { get; set; }
        public virtual DbSet<mUsers> mUsers { get; set; }
    
        public virtual ObjectResult<spmOperations_GetAll_Result> spmOperations_GetAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spmOperations_GetAll_Result>("spmOperations_GetAll");
        }
    
        public virtual ObjectResult<spmOperations_GetByID_Result> spmOperations_GetByID(Nullable<int> operationID)
        {
            var operationIDParameter = operationID.HasValue ?
                new ObjectParameter("OperationID", operationID) :
                new ObjectParameter("OperationID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spmOperations_GetByID_Result>("spmOperations_GetByID", operationIDParameter);
        }
    }
}
