//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppReportTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class mProfiles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mProfiles()
        {
            this.dUserProfiles = new HashSet<dUserProfiles>();
            this.mAccessLog = new HashSet<mAccessLog>();
            this.mOperations = new HashSet<mOperations>();
        }
    
        public int ProfileID { get; set; }
        public string Name { get; set; }
        public int ApplicationID { get; set; }
        public bool IsReadOnly { get; set; }
        public int StatusID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dUserProfiles> dUserProfiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mAccessLog> mAccessLog { get; set; }
        public virtual mApplications mApplications { get; set; }
        public virtual mStatus mStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mOperations> mOperations { get; set; }
    }
}
