//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppReportTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class mSmartCards
    {
        public string SmartCardID { get; set; }
        public string Pin { get; set; }
        public int UserID { get; set; }
        public int RoleID { get; set; }
        public System.DateTime CreationDate { get; set; }
        public System.DateTime Expiration { get; set; }
        public int StatusID { get; set; }
    
        public virtual mSmartCardRoles mSmartCardRoles { get; set; }
        public virtual mStatus mStatus { get; set; }
        public virtual mUsers mUsers { get; set; }
    }
}
