//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppReportTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class mUsers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mUsers()
        {
            this.dUserProfiles = new HashSet<dUserProfiles>();
            this.mAccessLog = new HashSet<mAccessLog>();
            this.mSmartCards = new HashSet<mSmartCards>();
            this.Delegation = new HashSet<Delegation>();
        }
    
        public int UserID { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public string Surname { get; set; }
        public string Address { get; set; }
        public Nullable<int> ZipCode { get; set; }
        public string Email { get; set; }
        public string Organization { get; set; }
        public string Position { get; set; }
        public string ShortName { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public int Sex { get; set; }
        public int StatusID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool IsReadOnly { get; set; }
        public bool IsFirstSession { get; set; }
        public bool IsActiveSession { get; set; }
        public System.DateTime LastLogin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dUserProfiles> dUserProfiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mAccessLog> mAccessLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mSmartCards> mSmartCards { get; set; }
        public virtual mStatus mStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Delegation> Delegation { get; set; }
    }
}
